# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   replication     ${DB_REPL_USER}                          trust
host    replication     ${DB_REPL_USER}  127.0.0.1/32            trust
host    replication     ${DB_REPL_USER}  ::1/128                 trust


