standby_mode = 'on'
primary_conninfo = 'host=db port=5432 user=${DB_REPL_USER} password=${DB_REPL_PASSWORD} sslmode=disable'
trigger_file = '/tmp/postgres.trigger'
standby_mode = 'on'
primary_conninfo = 'host=db port=5432 user= password= sslmode=disable'
trigger_file = '/tmp/postgres.trigger'
standby_mode = 'on'
primary_conninfo = 'host=db port=5432 user= password= sslmode=disable'
trigger_file = '/tmp/postgres.trigger'
standby_mode = 'on'
primary_conninfo = 'host=db port=5432 user= password= sslmode=disable'
trigger_file = '/tmp/postgres.trigger'
standby_mode = 'on'
primary_conninfo = 'host=db port=5432 user= password= sslmode=disable'
trigger_file = '/tmp/postgres.trigger'
standby_mode = 'on'
primary_conninfo = 'host=db port=5432 user= password= sslmode=disable'
trigger_file = '/tmp/postgres.trigger'
